// export const GET_SEARCH_DATA = 'GET_SEARCH_DATA'
// export const GET_PAGE_COUNT = 'GET_PAGE_COUNT'

export enum ActionType {
  GET_SEARCH_DATA = 'GET_SEARCH_DATA',
  GET_PAGE_COUNT = 'GET_PAGE_COUNT',
  GET_SEARCH_DATA_ERROR = 'GET_SEARCH_DATA_ERROR',
}
